version: '3.8'

services:
  # Node.js service
  node:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    working_dir: /usr/src/app
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - internalnet

  # React service
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - node
    networks:
      - internalnet

  # MySQL service
  mysql:
    # image: mysql:latest
    restart: unless-stopped
    build:
      context: ./db
      dockerfile: Dockerfile.mysql
    # command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yoga
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - internalnet
    # Script to run the mysql making connection and then running node,so as to node can connect to mysql  
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5

networks:
  internalnet:
    driver: bridge
